### ISSUE TITLE
property it puts items into bimaps (BiMapPropertiesTest) failed

### ISSUE THREAD

**Issue by mkaput** [mkaput/elixir-bimap#24]
```elixir
  1) property it puts items into bimaps (BiMapPropertiesTest)
     test/bimap_properties_test.exs:56
     Failed with generated values (after 2 successful runs):
     
         * Clause:    key_set <- nonempty(uniq_list_of(term()))
           Generated: [%{false => -0.5, #Reference<0.0.1.69648> => "}", "" => -1}, {:N2}]
         
         * Clause:    value_set <- uniq_list_of(term(), length: Enum.count(key_set))
           Generated: [7.5, -1]
         
         * Clause:    random_key <- term()
           Generated: 9.0
         
         * Clause:    random_value <- term()
           Generated: -1.0
     
     Expected truthy, got false
     code: assert BiMap.equal?(put_bimap, BiMap.new(put_regular_map))
     stacktrace:
       test/bimap_properties_test.exs:72: anonymous fn/5 in BiMapPropertiesTest."property it puts items into bimaps"/1
       (stream_data) lib/stream_data.ex:2148: StreamData.shrink_failure/6
       (stream_data) lib/stream_data.ex:2108: StreamData.check_all/7
       test/bimap_properties_test.exs:57: (test)
```

ref: https://travis-ci.com/github/mkaput/elixir-bimap/jobs/493002978

**Comment by mkaput** [comment]
bimap uses strict equality under the hood, and so should do our tests
